version: "3.0"

services:
  nginx:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - app
      - db
    ports:
      - 3030:3030

    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.8GB'

  app:
    depends_on:
     - db
    restart: always
    build: .
    env_file:
      - .env
    networks:
      - network
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.3'
          memory: '0.6GB'

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '1.5GB'

volumes:
  dbdata:
networks:
  network:
    driver: bridge