# Generated by Django 4.2.3 on 2023-09-07 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='favicon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Ícone'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
        ),
    ]
