# Generated by Django 4.2.3 on 2023-09-15 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='page',
            name='guarantee_of_satisfaction',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de garantia de satisfação'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web.page', verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'foco na mídia'), (2, 'foco no conteúdo')], db_index=True, verbose_name='Tipo de seção'),
        ),
    ]
