# Generated by Django 4.2.3 on 2023-09-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contact_full_name_page_guarantee_of_satisfaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesectioncontent',
            name='type',
        ),
        migrations.AlterField(
            model_name='pagesectioncontent',
            name='file',
            field=models.FileField(upload_to='upload/page/section', verbose_name='Arquivo'),
        ),
    ]
