# Generated by Django 4.2.3 on 2023-09-17 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_image_page_header_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='pagesectioncontent',
            name='file',
            field=models.FileField(upload_to='upload/page/section', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpeg', 'gif', 'jpg', 'webp', 'ico', 'svg', 'mp4', 'mov', 'wmv', 'webm', 'pdf', 'xlsx', 'xls', 'json', 'txt'))], verbose_name='Arquivo'),
        ),
    ]
