# Generated by Django 4.2.3 on 2023-08-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=500, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Subtítulo')),
                ('action', models.CharField(blank=True, max_length=500, null=True, verbose_name='Botão de ação')),
                ('image', models.ImageField(upload_to='upload/page', verbose_name='Imagem')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='upload/page', verbose_name='Imagem do selo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'imagem'), (2, 'texto')], db_index=True, verbose_name='Tipo de seção')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('order', models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web.page')),
            ],
            options={
                'verbose_name': 'Seção da página',
                'verbose_name_plural': 'Seções das páginas',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Preço')),
                ('number_of_installments', models.PositiveSmallIntegerField(null=True, verbose_name='Número de parcelas')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='upload/site', verbose_name='Imagem')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('enabled', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('icon', models.CharField(max_length=250, verbose_name='Ícone')),
                ('url', models.URLField(verbose_name='URL')),
                ('enabled', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='web.site')),
            ],
            options={
                'verbose_name': 'Mídia social',
                'verbose_name_plural': 'Mídias sociais',
            },
        ),
        migrations.CreateModel(
            name='PageSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'imagem'), (2, 'video')], db_index=True, verbose_name='Tipo de conteúdo')),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/page/section', verbose_name='Arquivo')),
                ('action', models.CharField(blank=True, max_length=500, null=True, verbose_name='Botão de ação')),
                ('enabled', models.BooleanField(db_index=True, default=False, verbose_name='Habilitado')),
                ('order', models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_contents', to='web.pagesection')),
            ],
            options={
                'verbose_name': 'Conteúdo da página',
                'verbose_name_plural': 'Conteúdos das páginas',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='page',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.product'),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='web.site'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=250, null=True, verbose_name='Email')),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Desconhecido'), (2, 'Dúvida'), (3, 'Sugestão'), (4, 'Crítica')], db_index=True, verbose_name='Rasão')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='web.page')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
