# Generated by Django 4.2.3 on 2023-07-31 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=500, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Subtítulo')),
                ('action', models.CharField(blank=True, max_length=500, null=True, verbose_name='Botão de ação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Preço')),
                ('number_of_installments', models.PositiveSmallIntegerField(null=True, verbose_name='Número de parcelas')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem do selo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'imagem'), (2, 'texto')], verbose_name='Tipo de seção')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('order', models.PositiveSmallIntegerField(null=True, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web.page')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('icon', models.CharField(max_length=250, verbose_name='Ícone')),
                ('url', models.URLField(verbose_name='URL')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='web.site')),
            ],
        ),
        migrations.CreateModel(
            name='PageSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
                ('action', models.CharField(blank=True, max_length=500, null=True, verbose_name='Botão de ação')),
                ('order', models.PositiveSmallIntegerField(null=True, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_contents', to='web.pagesection')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='web.site'),
        ),
    ]
