# Generated by Django 4.2.3 on 2023-08-25 16:48

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=500, verbose_name='Slug')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Subtítulo')),
                ('action', models.CharField(blank=True, max_length=500, null=True, verbose_name='Botão de ação')),
                ('image', models.ImageField(upload_to='upload/page', verbose_name='Imagem')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='upload/page', verbose_name='Imagem do selo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'imagem'), (2, 'texto')], db_index=True, verbose_name='Tipo de seção')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('order', models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web.page')),
            ],
            options={
                'verbose_name': 'Seção da página',
                'verbose_name_plural': 'Seções das páginas',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Preço')),
                ('number_of_installments', models.PositiveSmallIntegerField(null=True, verbose_name='Número de parcelas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='upload/site', verbose_name='Imagem')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('enabled', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Cor primária')),
                ('secondary_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Cor secundária')),
                ('error_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Cor Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tema do site',
                'verbose_name_plural': 'Temas do site',
            },
        ),
        migrations.CreateModel(
            name='SiteSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('icon', models.CharField(max_length=250, verbose_name='Ícone')),
                ('url', models.URLField(verbose_name='URL')),
                ('enabled', models.BooleanField(db_index=True, null=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='web.site')),
            ],
            options={
                'verbose_name': 'Mídia social',
                'verbose_name_plural': 'Mídias sociais',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='site_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='web.sitetheme'),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='web.product')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='PageSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'imagem'), (2, 'video')], db_index=True, verbose_name='Tipo de conteúdo')),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/page/section', verbose_name='Arquivo')),
                ('action', models.CharField(blank=True, max_length=500, null=True, verbose_name='Botão de ação')),
                ('enabled', models.BooleanField(db_index=True, default=False, verbose_name='Habilitado')),
                ('order', models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_contents', to='web.pagesection')),
            ],
            options={
                'verbose_name': 'Conteúdo da página',
                'verbose_name_plural': 'Conteúdos das páginas',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='page',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.product'),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='web.site'),
        ),
        migrations.CreateModel(
            name='GradientSiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('primary', 'Primário'), ('button', 'Botão')], db_index=True, max_length=10, verbose_name='Tipo')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Cor')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Porcentagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('site_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sitetheme')),
            ],
            options={
                'verbose_name': 'Gradiente do site',
                'verbose_name_plural': 'Gradientes do site',
                'ordering': ('type', 'percentage'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=250, null=True, verbose_name='Email')),
                ('reason', models.CharField(choices=[('UNKNOWN', 'Desconhecido'), ('DOUBT', 'Dúvida'), ('SUGGESTION', 'Sugestão'), ('CRITICIZE', 'Crítica')], db_index=True, max_length=20, verbose_name='Rasão')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='web.page')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
