# Generated by Django 4.2.3 on 2023-08-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Seção da página', 'verbose_name_plural': 'Seções das páginas'},
        ),
        migrations.AlterModelOptions(
            name='pagesectioncontent',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Conteúdo da página', 'verbose_name_plural': 'Conteúdos das páginas'},
        ),
        migrations.AlterModelOptions(
            name='sitesocialmedia',
            options={'verbose_name': 'Mídia social', 'verbose_name_plural': 'Mídias sociais'},
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/page', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='page',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='upload/page', verbose_name='Imagem do selo'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='pagesectioncontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/page/section', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='pagesectioncontent',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(upload_to='upload/site', verbose_name='Imagem'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, null=True, verbose_name='Email')),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Desconhecido'), (2, 'Dúvida'), (3, 'Sugestão'), (4, 'Crítica')], verbose_name='Rasão')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='web.page')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
