name: Docker CD

on:
  workflow_call:
    inputs:
      push:
        required: false
        type: boolean
        default: false
      image-name:
        required: false
        type: string
        default: ${{ github.repository }}
      image-tag:
        required: false
        type: string
        default: ${{ github.sha }}

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ inputs.image-name }}:${{ inputs.image-tag }}
      IMAGE_NAME_LATEST: ${{ inputs.image-name }}:latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Pull latest image
        run: |
          {
            docker pull ${{ env.IMAGE_NAME_LATEST }}
          } || {
            echo 'Latest image does not exists'
          }

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ inputs.push }}
          tags: ${{ env.IMAGE_NAME }}, ${{ env.IMAGE_NAME_LATEST }}
